### ISSUE TITLE
pyitau is not working

### ISSUE THREAD

**Issue by lucasrcezimbra** [lucasrcezimbra/pyitau#151]
pyitau is not working. Error:

```
Traceback (most recent call last):
  File "/home/lucas/workspace/cronjobs/itau_spreadsheet/__main__.py", line 101, in <module>
    main(initial_date)
  File "/home/lucas/workspace/cronjobs/itau_spreadsheet/__main__.py", line 31, in main
    itau.authenticate()
  File "/home/lucas/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyitau/main.py", line 32, in authenticate
    self._authenticate0()
  File "/home/lucas/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyitau/main.py", line 82, in _authenticate0
    self._id = page.id
  File "/home/lucas/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyitau/pages.py", line 26, in id
    return self._form.find('input', attrs={'name': 'portal'}).attrs['value']
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by lucasrcezimbra** [comment]
Fixed in version 1.0.2
